/**
 * domain-model-service
 * This is the domain model service of consort-group. It returns all objects defined in the corresponding swagger files.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@consort-it.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PropertyInfo } from './propertyInfo';

export interface DomainModel {
  /**
   * unique id of the domain model
   */
  id: string;
  /**
   * name of the model object
   */
  name: string;
  /**
   * name of the microservice the model belongs to
   */
  serviceName: string;
  properties: Array<PropertyInfo>;
  /**
   * Specifies the color of the header (as valid html color)
   */
  headerColor?: string;
  /**
   * Specifies the name of a google material icon which should be displayed on this model (optional). For full list see https://material.io/tools/icons/
   */
  iconName?: string;
  /**
   * The horizontal position of the Model object on the viewport
   */
  positionX?: number;
  /**
   * The vertical position of the Model object on the viewport
   */
  positionY?: number;
}
