/**
 * domain-model-service
 * This is the domain model service of consort-group. It returns all objects defined in the corresponding swagger files.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@consort-it.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ErrorResponse {
  /**
   * This error code should have the format 'DMS-XXX' where XXX is an integer. It is used to uniquely distinguish different error cases in order to display a suitable and translatable error message on the UI.
   */
  code: string;
  /**
   * Should contain a short, meaningful description of the error case. Might be displayed to the end user.
   */
  message: string;
}
