/**
 * domain-model-service
 * This is the domain model service of consort-group. It returns all objects defined in the corresponding swagger files.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@consort-it.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PropertyInfo {
  /**
   * name of the property.
   */
  name: string;
  /**
   * Type of the property. Can be any primitive type defined in swagger spec or the name of another domain model
   */
  type: string;
  /**
   * Indicates if this property is an array
   */
  isArray: boolean;
  /**
   * Indicates if this property is mandatory
   */
  isRequired: boolean;
}
