/**
 * Quality Backend
 * This services gathers Quality Gate information from different sources and prepares a summary report.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface QualityIndex {
  /**
   * The point in time when the status was retrieved. Should be in UTC.
   */
  generatedAt: Date;
  /**
   * Calculated health metric. Should be between 0 and 100.
   */
  value: number;
}
