/**
 * Quality Backend
 * This services gathers Quality Gate information from different sources and prepares a summary report.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QualityDetail } from './qualityDetail';

export interface QualityStatus {
  /**
   * This quality status refers to which system.
   */
  category: QualityStatus.CategoryEnum;
  /**
   * The status of this category or 'Unknown' if the status could not be retrieved.
   */
  status: QualityStatus.StatusEnum;
  /**
   * The number of issues Warning/Failure in this category.
   */
  issueCount?: number;
  /**
   * The point in time when the status was retrieved. Should be in UTC.
   */
  generatedAt: Date;
  /**
   * A dashboard url of the related metric.
   */
  ref?: string;
  details?: Array<QualityDetail>;
}
export namespace QualityStatus {
  export type CategoryEnum =
    | 'CodeQuality'
    | 'Builds'
    | 'Contracts'
    | 'Vulnerabilities'
    | 'Bugs'
    | 'SmokeTests'
    | 'End2End'
    | 'Logs';
  export const CategoryEnum = {
    CodeQuality: 'CodeQuality' as CategoryEnum,
    Builds: 'Builds' as CategoryEnum,
    Contracts: 'Contracts' as CategoryEnum,
    Vulnerabilities: 'Vulnerabilities' as CategoryEnum,
    Bugs: 'Bugs' as CategoryEnum,
    SmokeTests: 'SmokeTests' as CategoryEnum,
    End2End: 'End2End' as CategoryEnum,
    Logs: 'Logs' as CategoryEnum
  };
  export type StatusEnum = 'Passed' | 'Warning' | 'Failed' | 'Unknown';
  export const StatusEnum = {
    Passed: 'Passed' as StatusEnum,
    Warning: 'Warning' as StatusEnum,
    Failed: 'Failed' as StatusEnum,
    Unknown: 'Unknown' as StatusEnum
  };
}
