/**
 * Quality Backend
 * This services gathers Quality Gate information from different sources and prepares a summary report.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface StaticCodeQuality {
  /**
   * Cumulated amount of bugs.
   */
  bugs: number;
  /**
   * Cumulated amount of vulnerabilities.
   */
  vulnerabilities: number;
  /**
   * Cumulated amount of code smells.
   */
  codeSmells: number;
  /**
   * Cumulated amount of coverage in percent.
   */
  coverage: number;
  /**
   * The point in time when the status was retrieved. Should be in UTC.
   */
  generatedAt: Date;
}
