/**
 * Gitlab Adapter
 * This is the gitlab adapter service of consort-group. It gets files from gitlab and returns them when api request are made.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: paul.krugel@consort-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Metadata of a given object
 */
export interface GeneralMetadata {
  id?: string;
  shortId?: string;
  title?: string;
  createdAt?: string;
  parentIds?: Array<string>;
  message?: string;
  authorName?: string;
  authorEmail?: string;
  authoredDate?: string;
  committerName?: string;
  committerEmail?: string;
  committerDate?: string;
}
