/**
 * feature-toggle-service
 * The feature toggle service manages feature toggle settings for the microservices in different environments. It can read the current settings as well as change them.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FeatureToggle {
  /**
   * name of the feature
   */
  name: string;
  /**
   * description of the feature
   */
  description: string;
  /**
   * \"true\" if the toggle is activated, \"false\" otherwise
   */
  value: FeatureToggle.ValueEnum;
}
export namespace FeatureToggle {
  export type ValueEnum = 'on' | 'onToOff' | 'off' | 'offToOn';
  export const ValueEnum = {
    On: 'on' as ValueEnum,
    OnToOff: 'onToOff' as ValueEnum,
    Off: 'off' as ValueEnum,
    OffToOn: 'offToOn' as ValueEnum
  };
}
