/**
 * feature-toggle-service
 * The feature toggle service manages feature toggle settings for the microservices in different environments. It can read the current settings as well as change them.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: manuel.hiemer@consort-it.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FeatureToggle {
  /**
   * Name of the FeatureToggle
   */
  name: string;
  /**
   * Description of the feature
   */
  description: string;
  /**
   * Is this toggle activated or not
   */
  value: boolean;
}
