/**
 * AWS Cost API Adapter
 * This is an adapter service to proxy information from AWS Cost Explorer API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nicole.tornow@consort-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This array describes the values retrieved from a get resource-groups request
 */
export interface ResourceGroup extends Array<string> {}
