/**
 * Cloudwatch Logs Adapter
 * A microservice called cloudwatch-logs-adapter observing AWS logs from different microservices. It serves a specific amount of last log lines of corresponding microservice identified by name. Ticket at [http://swagger.io](http://swagger.io).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.renner@consort-it.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Group {
  /**
   * Group identifier or name for finding this Group.
   */
  logGroupName: string;
  /**
   * Group Creation Time
   */
  creationTime: Date;
  /**
   * Group Age in days
   */
  retentionInDays?: number;
  /**
   * Group metric filter count
   */
  metricFilterCount?: number;
  /**
   * Group Address Resolution Name
   */
  arn: string;
  /**
   * Group Size in Storage
   */
  storedBytes: number;
}
