/**
 * Cloudwatch Logs Adapter
 * A microservice called cloudwatch-logs-adapter observing AWS logs from different microservices. It serves a specific amount of last log lines of corresponding microservice identified by name. Ticket at [http://swagger.io](http://swagger.io).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.renner@consort-it.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LogEntry {
  /**
   * Log incident time
   */
  timestamp: Date;
  /**
   * Is this log containing critical information?
   */
  status: LogEntry.StatusEnum;
  /**
   * Log message
   */
  message: string;
}
export namespace LogEntry {
  export type StatusEnum = 'LOG' | 'INFO' | 'WARNING' | 'ERROR';
  export const StatusEnum = {
    LOG: 'LOG' as StatusEnum,
    INFO: 'INFO' as StatusEnum,
    WARNING: 'WARNING' as StatusEnum,
    ERROR: 'ERROR' as StatusEnum
  };
}
