/**
 * Cloudwatch Logs Adapter
 * A microservice called cloudwatch-logs-adapter observing AWS logs from different microservices. It serves a specific amount of last log lines of corresponding microservice identified by name. Ticket at [http://swagger.io](http://swagger.io).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.renner@consort-it.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Stream {
  /**
   * Stream identifier or name for finding this Stream.
   */
  logStreamName: string;
  /**
   * Stream Creation Time
   */
  creationTime: Date;
  /**
   * Stream information about first Event happened
   */
  firstEventTimestamp: Date;
  /**
   * Stream information about last Event happened
   */
  lastEventTimestamp: Date;
  /**
   * Stream information about last Event stored in logs
   */
  lastIngestionTime?: Date;
  /**
   * Stream upload sequence Token
   */
  uploadSequenceToken: string;
  /**
   * Stream Address Resolution Name
   */
  arn: Date;
  /**
   * Stream Size in Storage
   */
  storedBytes: number;
}
