/**
 * Jira Adapter API
 * An API for querying Jira
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Information about a Jira issue
 */
export interface JiraIssue {
  /**
   * Jira issue title
   */
  title: string;
  /**
   * When this issue was created or last updated (in UTC)
   */
  updated: Date;
  /**
   * The ID of the Jira issue
   */
  key: string;
  /**
   * Jira status of this issue
   */
  status: string;
  /**
   * The fully qualified url to view this JIRA issue.
   */
  url: string;
}
