/**
 * metadata-service
 * This is the metadata service of consort-group. It handels CRU(D)-operations for the application metadata.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: manuel.hiemer@consort-it.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ErrorResponse {
  /**
   * This error code should have the format 'MDS-XXX' where XXX is an integer. It is used to uniquely distinguish different error cases in order to display a suitable and translatable error message on the UI.
   */
  code: string;
  /**
   * Should contain a short, meaningful description of the error case. Might be displayed to the end user.
   */
  message: string;
}
