/**
 * metadata-service
 * This is the metadata service of consort-group. It handels CRU(D)-operations for the application metadata.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: manuel.hiemer@consort-it.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This entity will be used to create new Projects. A new uuid will be auto-generated by the server when creating a new Project.
 */
export interface NewProject {
  name: string;
  description?: string;
}
